openapi: 3.0.3
info:
  title: ProteinLens User Signup API
  description: API contracts for user signup feature (010-user-signup)
  version: 1.0.0
  
servers:
  - url: /api
    description: Azure Functions backend

paths:
  /signup/profile:
    post:
      summary: Complete user profile after B2C signup
      description: |
        Called after successful B2C authentication to create/update local user profile.
        Creates ConsentRecord entries for accepted consents.
        Requires valid B2C access token.
      operationId: completeSignupProfile
      tags:
        - signup
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupProfileRequest'
      responses:
        '200':
          description: Profile created/updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Invalid or missing access token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Email already registered (duplicate)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DuplicateEmailError'

  /signup/check-email:
    post:
      summary: Check if email is available for signup
      description: |
        Checks email availability at form submission time (not real-time).
        Rate limited to prevent enumeration attacks.
      operationId: checkEmailAvailability
      tags:
        - signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 320
                captchaToken:
                  type: string
                  description: hCaptcha token (required after 3 failed attempts)
      responses:
        '200':
          description: Email availability result
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: boolean
                  suggestion:
                    type: string
                    description: Email typo suggestion if detected
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitError'

  /signup/validate-password:
    post:
      summary: Validate password against breach list
      description: |
        Uses HIBP k-Anonymity to check if password appears in known breaches.
        Frontend should call this, but backend validates again before B2C signup.
      operationId: validatePassword
      tags:
        - signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - passwordPrefix
              properties:
                passwordPrefix:
                  type: string
                  description: First 5 characters of SHA-1 hash of password
                  minLength: 5
                  maxLength: 5
                  pattern: '^[0-9A-F]{5}$'
      responses:
        '200':
          description: Breach check result
          content:
            application/json:
              schema:
                type: object
                properties:
                  breached:
                    type: boolean
                  occurrences:
                    type: integer
                    description: Number of times password found in breaches (if breached)

  /signup/consent:
    post:
      summary: Record user consent
      description: Records consent for Terms of Service, Privacy Policy, or Marketing
      operationId: recordConsent
      tags:
        - signup
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentRequest'
      responses:
        '200':
          description: Consent recorded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentRecord'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Get user's consent records
      description: Returns all consent records for the authenticated user
      operationId: getUserConsents
      tags:
        - signup
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of consent records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConsentRecord'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /signup/resend-verification:
    post:
      summary: Resend email verification
      description: |
        Triggers B2C to resend verification email.
        Rate limited to 10 requests per email per day.
      operationId: resendVerification
      tags:
        - signup
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Verification email sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Verification email sent. Please check your inbox and spam folder.
                  nextAllowedAt:
                    type: string
                    format: date-time
                    description: When next resend is allowed
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Azure B2C access token

  schemas:
    SignupProfileRequest:
      type: object
      required:
        - firstName
        - lastName
        - acceptedTermsVersion
        - acceptedPrivacyVersion
      properties:
        firstName:
          type: string
          minLength: 1
          maxLength: 50
          pattern: '^[a-zA-Z\s\-'']+$'
        lastName:
          type: string
          minLength: 1
          maxLength: 50
          pattern: '^[a-zA-Z\s\-'']+$'
        organizationName:
          type: string
          maxLength: 100
        phone:
          type: string
          pattern: '^\+?[1-9]\d{1,14}$'
        acceptedTermsVersion:
          type: string
          description: Version of Terms of Service accepted
          example: "2025-01-01"
        acceptedPrivacyVersion:
          type: string
          description: Version of Privacy Policy accepted
          example: "2025-01-01"
        acceptedMarketing:
          type: boolean
          default: false

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        organizationName:
          type: string
          nullable: true
        phone:
          type: string
          nullable: true
        emailVerified:
          type: boolean
        profileCompleted:
          type: boolean
        plan:
          type: string
          enum: [FREE, PRO]
        createdAt:
          type: string
          format: date-time

    ConsentRequest:
      type: object
      required:
        - consentType
        - documentVersion
      properties:
        consentType:
          type: string
          enum: [TERMS_OF_SERVICE, PRIVACY_POLICY, MARKETING_EMAILS]
        documentVersion:
          type: string
          maxLength: 20
        granted:
          type: boolean
          default: true
          description: False to revoke consent

    ConsentRecord:
      type: object
      properties:
        id:
          type: string
          format: uuid
        consentType:
          type: string
          enum: [TERMS_OF_SERVICE, PRIVACY_POLICY, MARKETING_EMAILS]
        documentVersion:
          type: string
        grantedAt:
          type: string
          format: date-time
        revokedAt:
          type: string
          format: date-time
          nullable: true

    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: Validation failed
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

    DuplicateEmailError:
      type: object
      properties:
        error:
          type: string
          example: Email already registered
        actions:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum: [signin, reset_password]
              label:
                type: string
              url:
                type: string

    RateLimitError:
      type: object
      properties:
        error:
          type: string
          example: Too many requests
        retryAfter:
          type: integer
          description: Seconds until next request allowed
        nextAllowedAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
