/**
 * Blog Content Index
 * 
 * Centralized blog post metadata and content for SEO.
 * Posts are organized by category for easy management.
 */

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  keywords: string;
  category: 'ai-tracking' | 'protein-goals' | 'macro-basics' | 'tdee-calories' | 'real-life-tracking';
  publishedAt: string;
  updatedAt: string;
  readingTime: number; // minutes
  featured?: boolean;
}

// Blog post metadata (content is in separate files)
export const blogPosts: BlogPost[] = [
  // === AI + Photo Tracking (High Intent, Unique Angle) ===
  {
    slug: 'how-to-track-macros-from-photo',
    title: 'Track Macros from a Photo: Accuracy Guide',
    description: 'Learn how AI photo macro tracking works, what accuracy you can realistically expect, and tips for getting the best results from food photo analysis.',
    keywords: 'track macros from photo, AI macro tracking, food photo analysis, macro tracking app, photo nutrition tracker',
    category: 'ai-tracking',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 8,
    featured: true,
  },
  {
    slug: 'photo-macro-tracking-vs-barcode-scanning',
    title: 'Photo vs Barcode Tracking: Speed & Accuracy',
    description: 'Compare AI photo macro tracking to barcode scanning. Discover which method is faster, more accurate, and better suited for different meal types.',
    keywords: 'photo macro tracking, barcode scanning, macro tracking comparison, food tracking methods, AI vs barcode',
    category: 'ai-tracking',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 7,
  },
  {
    slug: 'best-lighting-angles-food-photo-macros',
    title: 'Best Lighting & Angles for Food Photo Macros',
    description: 'Get more accurate macro estimates from food photos with these simple lighting and angle tips. Improve your AI food tracking results instantly.',
    keywords: 'food photo tips, macro tracking accuracy, food photography for tracking, AI food scan tips, better food photos',
    category: 'ai-tracking',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 5,
  },
  {
    slug: 'estimate-portion-sizes-from-photos',
    title: 'Estimate Portion Sizes from Photos (Visual Tricks)',
    description: 'Master portion estimation with visual comparison tricks. Learn to estimate serving sizes accurately using everyday objects and hand measurements.',
    keywords: 'estimate portion sizes, visual portion guide, portion size photos, serving size estimation, portion control',
    category: 'ai-tracking',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 6,
  },
  {
    slug: 'common-ai-food-scan-mistakes',
    title: 'Common AI Food Scan Mistakes (And How to Fix Them)',
    description: 'Avoid the most common AI food scanning errors. Learn why macro estimates can be off and simple fixes to improve your tracking accuracy.',
    keywords: 'AI food scan mistakes, macro tracking errors, food tracking accuracy, fix macro estimates, AI nutrition errors',
    category: 'ai-tracking',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 7,
  },
  {
    slug: 'track-restaurant-meals-unknown-ingredients',
    title: 'Track Restaurant Meals with Unknown Ingredients',
    description: 'Track macros at restaurants without stressing over hidden ingredients. Practical strategies for eating out while staying on track with your goals.',
    keywords: 'track restaurant meals, macros eating out, restaurant macro tracking, dining out macros, unknown ingredients tracking',
    category: 'ai-tracking',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 8,
  },
  
  // === Protein Goals (High Search Volume) ===
  {
    slug: 'how-much-protein-per-day',
    title: 'How Much Protein Per Day? Calculator + Examples',
    description: 'Calculate your daily protein needs based on your weight, activity level, and goals. Includes practical examples and a free calculator.',
    keywords: 'how much protein per day, daily protein intake, protein calculator, protein requirements, protein needs',
    category: 'protein-goals',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 9,
    featured: true,
  },
  {
    slug: 'protein-for-fat-loss',
    title: 'Protein Per Day for Fat Loss: Does More Always Help?',
    description: 'Discover the optimal protein intake for fat loss. Learn why protein matters for preserving muscle, controlling hunger, and burning more calories.',
    keywords: 'protein for fat loss, protein while dieting, high protein weight loss, protein cutting, lose fat keep muscle',
    category: 'protein-goals',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 8,
  },
  {
    slug: 'protein-for-muscle-gain',
    title: 'Protein for Muscle Gain: Targets by Bodyweight',
    description: 'Find your optimal protein intake for building muscle. Science-backed recommendations with practical targets based on your bodyweight.',
    keywords: 'protein for muscle gain, protein bodybuilding, muscle building protein, protein bulking, how much protein muscle',
    category: 'protein-goals',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 8,
  },
  {
    slug: 'high-protein-breakfast-ideas',
    title: 'High-Protein Breakfast Ideas (Quick, Cheap, Easy to Track)',
    description: '15+ high-protein breakfast ideas that are quick to make, budget-friendly, and easy to track. Start your day with 30-50g protein.',
    keywords: 'high protein breakfast, protein breakfast ideas, quick protein breakfast, easy high protein breakfast, breakfast macros',
    category: 'protein-goals',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 10,
  },
  
  // === Macro Basics (Beginner Traffic) ===
  {
    slug: 'what-are-macros',
    title: 'What Are Macros? Protein, Carbs & Fat Explained',
    description: 'Learn what macros are and why they matter. Simple explanations of protein, carbohydrates, and fat with real food examples.',
    keywords: 'what are macros, macronutrients explained, protein carbs fat, macro basics, macros for beginners',
    category: 'macro-basics',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 7,
    featured: true,
  },
  {
    slug: 'how-to-calculate-macros-weight-loss',
    title: 'How to Calculate Macros for Weight Loss (Step-by-Step)',
    description: 'A complete guide to calculating your macros for weight loss. Step-by-step instructions with examples and a free calculator.',
    keywords: 'calculate macros weight loss, macro calculator, weight loss macros, macro diet, counting macros to lose weight',
    category: 'macro-basics',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 10,
  },
  {
    slug: 'calories-vs-macros',
    title: 'Calories vs Macros: What Matters Most for Results?',
    description: 'Should you count calories or macros? Learn which approach works better for different goals and how to decide what to track.',
    keywords: 'calories vs macros, count calories or macros, macro tracking vs calorie counting, what to track for weight loss',
    category: 'macro-basics',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 8,
  },
  
  // === TDEE & Calories (Evergreen) ===
  {
    slug: 'what-is-tdee',
    title: 'What Is TDEE? (And How to Calculate It Accurately)',
    description: 'Understand TDEE (Total Daily Energy Expenditure) and learn how to calculate yours accurately. The foundation for any diet plan.',
    keywords: 'what is TDEE, TDEE calculator, total daily energy expenditure, calculate TDEE, daily calorie burn',
    category: 'tdee-calories',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 8,
  },
  {
    slug: 'weight-loss-plateau-reasons',
    title: 'Weight Loss Plateau: 9 Reasons the Scale Stopped Moving',
    description: 'Stuck at a weight loss plateau? Discover the 9 most common reasons your weight stopped dropping and exactly how to break through.',
    keywords: 'weight loss plateau, scale not moving, plateau weight loss, stuck losing weight, break weight loss plateau',
    category: 'tdee-calories',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 11,
  },
  
  // === Real-Life Tracking (High Conversion) ===
  {
    slug: 'track-macros-without-food-scale',
    title: 'Track Macros Without a Food Scale (Stay Consistent)',
    description: 'Track macros accurately without weighing everything. Learn practical estimation methods that keep you consistent without obsessing.',
    keywords: 'track macros without scale, no food scale macros, estimate portions, macro tracking without weighing',
    category: 'real-life-tracking',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 7,
  },
  {
    slug: 'track-macros-eating-out',
    title: 'How to Track Macros When You Eat Out 3+ Times a Week',
    description: 'Love eating out? Learn practical strategies to track macros at restaurants, fast food, and social dinners without derailing your progress.',
    keywords: 'track macros eating out, restaurant macro tracking, macros dining out, eating out on a diet',
    category: 'real-life-tracking',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 9,
  },
  {
    slug: 'macro-tracking-busy-people',
    title: 'Macro Tracking for Busy People: The 80/20 Way',
    description: 'Too busy to track every gram? Learn the 80/20 approach to macro tracking that gets results without taking over your life.',
    keywords: 'macro tracking busy, simple macro tracking, easy macro counting, 80/20 macro tracking, quick macro tracking',
    category: 'real-life-tracking',
    publishedAt: '2026-02-03',
    updatedAt: '2026-02-03',
    readingTime: 8,
  },
  // === Comparison / Alternatives (High Intent, Bottom of Funnel) ===
  {
    slug: 'proteinlens-vs-myfitnesspal',
    title: 'ProteinLens vs MyFitnessPal — 2026 Comparison',
    description: 'Honest comparison of ProteinLens AI photo tracking vs MyFitnessPal manual entry. Features, accuracy, pricing, and who should use what.',
    keywords: 'proteinlens vs myfitnesspal, myfitnesspal alternative, best macro tracker 2026, AI food tracker vs myfitnesspal, photo macro tracker',
    category: 'ai-tracking',
    publishedAt: '2026-02-26',
    updatedAt: '2026-02-26',
    readingTime: 7,
    featured: true,
  },
  {
    slug: 'proteinlens-vs-cronometer',
    title: 'ProteinLens vs Cronometer — Best Macro Tracker for 2026?',
    description: 'Comparing ProteinLens AI photo tracking with Cronometer\'s detailed micronutrient database. Speed vs precision — which tracker fits your goals?',
    keywords: 'proteinlens vs cronometer, cronometer alternative, best macro tracker 2026, AI macro tracker vs cronometer, fast nutrition tracker',
    category: 'ai-tracking',
    publishedAt: '2026-02-27',
    updatedAt: '2026-02-27',
    readingTime: 7,
  },
  {
    slug: 'proteinlens-vs-lose-it',
    title: 'ProteinLens vs Lose It! — Which Tracker Wins?',
    description: 'ProteinLens AI photo tracking vs Lose It! barcode scanning. Compare speed, accuracy, pricing, and which approach keeps you consistent.',
    keywords: 'proteinlens vs lose it, lose it alternative, best food tracker 2026, AI food tracker vs lose it, photo macro tracker',
    category: 'ai-tracking',
    publishedAt: '2026-02-27',
    updatedAt: '2026-02-27',
    readingTime: 8,
  },
  {
    slug: 'best-macro-tracking-apps-2026',
    title: 'Best Macro Tracking Apps 2026 — Top 7 Compared',
    description: 'We tested the 7 best macro tracking apps of 2026 — from AI photo scanning to barcode trackers. Find out which fits your goals and lifestyle.',
    keywords: 'best macro tracking app 2026, best nutrition tracker, macro counting app comparison, top food tracking apps, calorie counter app review',
    category: 'ai-tracking',
    publishedAt: '2026-03-01',
    updatedAt: '2026-03-01',
    readingTime: 10,
    featured: true,
  },
  {
    slug: 'how-ai-food-scanning-works',
    title: 'How AI Food Scanning Works — Behind ProteinLens',
    description: 'Curious how AI identifies food from a photo and estimates macros? We break down the image recognition, portion estimation, and nutritional mapping behind it.',
    keywords: 'how AI food scanning works, AI nutrition tracker technology, food image recognition, AI macro estimation, photo food tracking explained',
    category: 'ai-tracking',
    publishedAt: '2026-03-01',
    updatedAt: '2026-03-01',
    readingTime: 7,
  },
  {
    slug: 'why-you-quit-macro-tracking',
    title: 'Why You Keep Quitting Macro Tracking (And How to Fix It)',
    description: 'Most people abandon macro tracking within a week. Here are the 6 real reasons why — and practical fixes that actually make tracking stick.',
    keywords: 'why I quit macro tracking, macro tracking too hard, how to stick with macro tracking, food tracking motivation, easiest way to track macros',
    category: 'macro-basics',
    publishedAt: '2026-03-01',
    updatedAt: '2026-03-01',
    readingTime: 8,
  },
  {
    slug: 'scan-menu-for-protein',
    title: 'How to Scan a Menu for Protein Content',
    description: 'Use AI food scanning to track protein at restaurants. Snap a photo of your meal and get instant macro estimates — no nutrition labels needed.',
    keywords: 'scan menu for protein, protein scanner, scan food for protein, restaurant protein tracking, AI food scan, protein counter restaurant',
    category: 'ai-tracking',
    publishedAt: '2026-04-12',
    updatedAt: '2026-04-12',
    readingTime: 7,
  },
  {
    slug: 'protein-calculator-for-seniors',
    title: 'Protein Calculator for Seniors (60+)',
    description: 'How much protein do older adults need? Evidence-based protein targets for healthy aging, sarcopenia prevention, and maintaining strength after 60.',
    keywords: 'protein calculator seniors, protein for older adults, how much protein over 60, sarcopenia protein, elderly protein needs, senior protein intake',
    category: 'protein-goals',
    publishedAt: '2026-04-12',
    updatedAt: '2026-04-12',
    readingTime: 9,
  },
  {
    slug: 'fifty-grams-protein-breakfast',
    title: '50g Protein Breakfast: 10 Easy Recipes',
    description: '10 breakfasts that hit 50 grams of protein — from 3-minute shakes to weekend meals. Quick, cheap, and actually filling.',
    keywords: '50 grams protein breakfast, 50g protein breakfast, high protein breakfast 50g, how to get 50 grams of protein for breakfast, protein breakfast ideas',
    category: 'protein-goals',
    publishedAt: '2026-04-12',
    updatedAt: '2026-04-12',
    readingTime: 8,
  },
  {
    slug: 'photo-vs-manual-calorie-counting',
    title: 'Photo vs Manual Calorie Counting',
    description: 'AI photo tracking vs manual food logging: accuracy, speed, and consistency compared. Which calorie counting method is better for real results?',
    keywords: 'photo calorie counting, manual calorie tracking, AI food tracking vs manual, calorie counting methods, best way to count calories',
    category: 'ai-tracking',
    publishedAt: '2026-04-12',
    updatedAt: '2026-04-12',
    readingTime: 7,
  },
  {
    slug: 'high-protein-meal-prep',
    title: 'High-Protein Meal Prep: 5 Recipes for the Week',
    description: 'Complete meal prep guide with 5 high-protein recipes (30-50g each). Cook once on Sunday, eat all week. Includes macros, shopping list, and storage tips.',
    keywords: 'high protein meal prep, meal prep recipes, protein meal prep, weekly meal prep, meal prep for muscle gain',
    category: 'protein-goals',
    publishedAt: '2026-04-12',
    updatedAt: '2026-04-12',
    readingTime: 9,
  },
  {
    slug: 'how-much-protein-per-kg',
    title: 'How Much Protein Per Kg of Body Weight?',
    description: 'Evidence-based protein per kg recommendations by goal: 0.8g/kg (sedentary) to 2.4g/kg (fat loss). Includes tables for 7 populations with research sources.',
    keywords: 'protein per kg, protein per kilogram, how much protein per kg, protein intake per kg body weight, protein g/kg',
    category: 'protein-goals',
    publishedAt: '2026-04-12',
    updatedAt: '2026-04-12',
    readingTime: 10,
    featured: true,
  },
  {
    slug: 'ai-nutrition-tracking-accuracy',
    title: 'How Accurate Is AI Nutrition Tracking?',
    description: 'Honest breakdown of AI food tracking accuracy: 85-95% food ID, ±15-25% portions, ±15-30% macros. How it compares to manual logging and food scales.',
    keywords: 'AI nutrition tracking accuracy, food recognition accuracy, AI calorie counting, photo tracking accuracy, is AI food tracking accurate',
    category: 'ai-tracking',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 9,
    featured: true,
  },
  {
    slug: 'best-macro-split-for-weight-loss',
    title: 'Best Macro Split for Fat Loss (Evidence-Based)',
    description: 'Research-backed macro split for fat loss: 30-35% protein, 20-30% fat, rest carbs. Includes examples, adjustment tips, and 5 split approaches compared.',
    keywords: 'best macro split for weight loss, fat loss macros, macro ratio for cutting, weight loss macro split, optimal macros for fat loss',
    category: 'macro-basics',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 8,
  },
  {
    slug: 'track-macros-without-counting',
    title: 'Track Macros Without Counting Every Gram',
    description: 'Hit your macros without obsessive counting: hand portions, plate method, meal rotation, protein-only tracking, and AI spot-checks. Practical, sustainable methods.',
    keywords: 'track macros without counting, easy macro tracking, hand portion method, macro tracking without scale, simple macro tracking',
    category: 'real-life-tracking',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 9,
  },
  {
    slug: 'protein-timing-does-it-matter',
    title: 'Protein Timing: Does It Actually Matter?',
    description: 'The anabolic window myth debunked. Research shows total daily protein matters more than timing — but distribution across meals does help. Evidence-based guide.',
    keywords: 'protein timing, anabolic window, when to eat protein, post workout protein, protein meal timing',
    category: 'protein-goals',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 8,
  },
  {
    slug: 'how-to-read-nutrition-labels',
    title: 'How to Read Nutrition Labels for Macros',
    description: 'The 5 numbers that matter on a nutrition label: serving size, calories, protein, carbs, fat. Plus common label traps and speed hacks for macro trackers.',
    keywords: 'how to read nutrition labels, nutrition label macros, food label guide, reading nutrition facts, macro tracking labels',
    category: 'macro-basics',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 8,
  },
  {
    slug: 'vegan-protein-sources-complete',
    title: 'Vegan Protein Sources: Complete Guide',
    description: 'Hit 150g+ protein on a vegan diet. Ranked protein sources by density, sample meal plan, amino acid pairing, and common mistakes plant-based athletes make.',
    keywords: 'vegan protein sources, plant based protein, best vegan protein foods, vegan protein guide, high protein vegan diet',
    category: 'protein-goals',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 10,
    featured: true,
  },
  // === PROGRAMMATIC CONTENT — Food-specific protein/calorie guides ===
  {
    slug: 'protein-in-eggs',
    title: 'How Much Protein in Eggs? Complete Guide',
    description: 'One large egg has 6.3g protein. Full breakdown of whole eggs, whites, sizes, and the best ways to cook eggs for maximum protein absorption.',
    keywords: 'protein in eggs, how much protein in an egg, egg protein content, egg whites protein, protein in boiled egg',
    category: 'protein-goals',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 7,
  },
  {
    slug: 'protein-in-chicken-breast',
    title: 'Protein in Chicken Breast: Nutrition Facts',
    description: 'Chicken breast has 31g protein per 100g cooked. Full breakdown by cooking method, skin on/off, and how it compares to thighs, turkey, and other meats.',
    keywords: 'protein in chicken breast, chicken breast protein, how much protein in chicken, chicken breast nutrition, chicken breast macros',
    category: 'protein-goals',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 7,
  },
  {
    slug: 'protein-in-greek-yogurt',
    title: 'Protein in Greek Yogurt: Brands Compared',
    description: 'Greek yogurt has 10-18g protein per serving depending on brand and type. Full comparison of Fage, Chobani, Skyr, regular yogurt, and high-protein options.',
    keywords: 'protein in greek yogurt, greek yogurt protein, best greek yogurt for protein, high protein yogurt, skyr vs greek yogurt protein',
    category: 'protein-goals',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 7,
  },
  {
    slug: 'calories-in-rice',
    title: 'Calories & Macros in Rice (All Types)',
    description: 'White rice: 130 cal per 100g cooked. Brown rice: 112 cal. Full macro breakdown for basmati, jasmine, sushi, wild, and cauliflower rice.',
    keywords: 'calories in rice, rice calories, macros in rice, white rice calories, brown rice macros, rice nutrition facts',
    category: 'macro-basics',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 6,
  },
  {
    slug: 'calories-in-banana',
    title: 'Calories & Macros in Bananas by Size',
    description: 'A medium banana has 105 calories and 1.3g protein. Full macro breakdown by size, ripeness effects, and best uses for fitness goals.',
    keywords: 'calories in banana, banana calories, banana macros, banana nutrition, banana carbs, banana protein',
    category: 'macro-basics',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 5,
  },
  {
    slug: 'protein-in-salmon',
    title: 'Protein in Salmon: Nutrition Breakdown',
    description: 'Salmon has 25g protein per 100g cooked. Full macro comparison of Atlantic vs sockeye, wild vs farmed, smoked salmon, and canned salmon.',
    keywords: 'protein in salmon, salmon protein, salmon macros, salmon nutrition, wild salmon vs farmed protein, smoked salmon protein',
    category: 'protein-goals',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 6,
  },
  {
    slug: 'protein-in-oats',
    title: 'Protein in Oats & Oatmeal: Maximize It',
    description: 'Oats have 13g protein per 100g dry (5g per serving). How to boost oatmeal to 30g+ protein with add-ins. Overnight oats and protein oats.',
    keywords: 'protein in oats, oatmeal protein, protein in oatmeal, high protein oatmeal, protein overnight oats, oats macros',
    category: 'protein-goals',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 6,
  },
  // === PROGRAMMATIC CONTENT — Goal-specific & educational ===
  {
    slug: 'intermittent-fasting-macros',
    title: 'Intermittent Fasting & Macros: Complete Guide',
    description: 'How to hit your macro targets while intermittent fasting. 16:8, 20:4, and OMAD meal plans with protein timing and common IF mistakes.',
    keywords: 'intermittent fasting macros, IF macros, 16 8 macros, intermittent fasting protein, fasting and muscle, OMAD macros',
    category: 'macro-basics',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 9,
  },
  {
    slug: 'how-many-calories-to-build-muscle',
    title: 'How Many Calories to Build Muscle?',
    description: 'A surplus of 200-500 calories above maintenance builds muscle efficiently. Calculate bulking calories, avoid excess fat gain, and track progress.',
    keywords: 'calories to build muscle, bulking calories, calorie surplus for muscle, how many calories to gain muscle, lean bulk calories',
    category: 'tdee-calories',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 8,
  },
  {
    slug: 'what-is-bmr',
    title: 'What Is BMR? Basal Metabolic Rate Explained',
    description: 'BMR is the calories your body burns at rest. Learn how BMR is calculated (Mifflin-St Jeor), how it differs from TDEE, and why it matters for weight loss.',
    keywords: 'what is bmr, basal metabolic rate, bmr explained, bmr vs tdee, how to calculate bmr, bmr meaning',
    category: 'tdee-calories',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 7,
  },
  {
    slug: 'protein-for-women',
    title: 'Protein for Women: How Much Do You Need?',
    description: 'Women need 1.2-2.0g protein per kg for fitness goals. Debunking the bulky myth, pregnancy needs, menopause considerations, and a sample 120g protein day.',
    keywords: 'protein for women, how much protein women, female protein intake, protein women muscle, women protein requirements',
    category: 'protein-goals',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 8,
  },
  {
    slug: 'pre-workout-nutrition',
    title: 'What to Eat Before a Workout (Macros Guide)',
    description: 'Ideal pre-workout meal: 0.4g/kg protein + 0.5-1g/kg carbs, 1-3 hours before training. Timing guides, quick options, and fasted training advice.',
    keywords: 'pre workout nutrition, what to eat before workout, pre workout meal, pre workout macros, best food before gym',
    category: 'macro-basics',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 7,
  },
  {
    slug: 'track-macros-while-traveling',
    title: 'How to Track Macros While Traveling',
    description: 'Stay on track while traveling. Airport food, hotel breakfasts, street food, and restaurant strategies for tracking macros on the road.',
    keywords: 'track macros traveling, macro tracking travel, how to track macros on vacation, travel nutrition tips, eating healthy while traveling',
    category: 'real-life-tracking',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 7,
  },
  {
    slug: 'protein-in-beans-and-lentils',
    title: 'Protein in Beans & Lentils (All Types)',
    description: 'Lentils have 9g protein per 100g cooked. Full breakdown of chickpeas, black beans, kidney beans, edamame, and the best bean/grain combos.',
    keywords: 'protein in beans, protein in lentils, beans protein content, lentils protein, chickpea protein, bean protein chart',
    category: 'protein-goals',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 6,
  },
  {
    slug: 'how-to-count-macros-beginners',
    title: 'How to Count Macros: Beginner Guide (2026)',
    description: 'Complete beginner guide to macro counting. Calculate your targets, choose a tracking method, navigate your first week, and avoid common mistakes.',
    keywords: 'how to count macros, macro counting for beginners, start counting macros, beginner macro tracking, macros 101',
    category: 'macro-basics',
    publishedAt: '2026-04-28',
    updatedAt: '2026-04-28',
    readingTime: 10,
    featured: true,
  },
];

// Helper functions
export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find(post => post.slug === slug);
}

export function getBlogPostsByCategory(category: BlogPost['category']): BlogPost[] {
  return blogPosts.filter(post => post.category === category);
}

export function getFeaturedPosts(): BlogPost[] {
  return blogPosts.filter(post => post.featured);
}

export function getRecentPosts(limit: number = 10): BlogPost[] {
  return [...blogPosts]
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
    .slice(0, limit);
}

export const categoryLabels: Record<BlogPost['category'], string> = {
  'ai-tracking': 'AI & Photo Tracking',
  'protein-goals': 'Protein Goals',
  'macro-basics': 'Macro Basics',
  'tdee-calories': 'TDEE & Calories',
  'real-life-tracking': 'Real-Life Tracking',
};
